# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cee36c1639ca806c633db777b696ff9be40656b08bfccf9138b24390978e9fef67162073ac177356b01a109cbbfae8a8427a2fb40906d758bfc5e32ace78691

test:
  secret_key_base: 76331f6c6696f24c890a9ffb114346e1d35ad50a610eb7d9204ca6ef3584dd01b8035c02060f7208e5738509b820ce4e7cfc0554dd4d926b56e476a14795aa30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
